// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Login Using Email
export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

// Me Loading
export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

// ALl Users
export const ALL_USERS_LOADING = "ALL_USERS_LOADING";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

// All Questions
export const ALL_QUESTIONS_LOADING = "ALL_QUESTIONS_LOADING";
export const ALL_QUESTIONS_SUCCESS = "ALL_QUESTIONS_SUCCESS";
export const ALL_QUESTIONS_FAIL = "ALL_QUESTIONS_FAIL";

// Delete Question
export const DELETE_QUESTION_LOADING = "DELETE_QUESTION_LOADING";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";

// All Solution
export const ALL_SOLUTIONS_LOADING = "ALL_SOLUTIONS_LOADING";
export const ALL_SOLUTIONS_SUCCESS = "ALL_SOLUTIONS_SUCCESS";
export const ALL_SOLUTIONS_FAIL = "ALL_SOLUTIONS_FAIL";

// Delete Solution
export const DELETE_SOLUTION_LOADING = "DELETE_SOLUTION_LOADING";
export const DELETE_SOLUTION_SUCCESS = "DELETE_SOLUTION_SUCCESS";
export const DELETE_SOLUTION_FAIL = "DELETE_SOLUTION_FAIL";

// ALL Categories
export const ALL_CATEGORIES_LOADING = "ALL_CATEGORIES_LOADING";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

// New Category
export const ADD_NEW_CATEGORY_LOADING = "ADD_NEW_CATEGORY_LOADING";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAIL = "ADD_NEW_CATEGORY_FAIL";

// Update Category
export const UPDATE_CATEGORY_LOADING = "UPDATE_CATEGORY_LOADING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

// Delete Category
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

// Get All Admins
export const ALL_ADMINS_LOADING = "ALL_ADMINS_LOADING";
export const ALL_ADMINS_SUCCESS = "ALL_ADMINS_SUCCESS";
export const ALL_ADMINS_FAIL = "ALL_ADMINS_FAIL";

// Delete Admin User
export const DELETE_ADMIN_USER_LOADING = "DELETE_ADMIN_USER_LOADING ";
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS";
export const DELETE_ADMIN_USER_FAIL = "DELETE_ADMIN_USER_FAIL";

// Create Admin
export const CREATE_ADMIN_LOADING = "CREATE_ADMIN_LOADING";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";

//Delete User
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// Ban Toggle
export const BAN_TOGGLE_USER_LOADING = "BAN_TOGGLE_USER_LOADING";
export const BAN_TOGGLE_USER_SUCCESS = "BAN_TOGGLE_USER_SUCCESS";
export const BAN_TOGGLE_USER_FAIL = "BAN_TOGGLE_USER_FAIL";

// Hide Unhide Solution
export const HIDE_UNHIDE_SOLUTION_LOADING = "HIDE_UNHIDE_SOLUTION_LOADING";
export const HIDE_UNHIDE_SOLUTION_SUCCESS = "HIDE_UNHIDE_SOLUTION_SUCCESS";
export const HIDE_UNHIDE_SOLUTION_FAIL = "HIDE_UNHIDE_SOLUTION_FAIL";

// Hide Unhide Question
export const HIDE_UNHIDE_QUESTION_LOADING = "HIDE_UNHIDE_QUESTION_LOADING";
export const HIDE_UNHIDE_QUESTION_SUCCESS = "HIDE_UNHIDE_QUESTION_SUCCESS";
export const HIDE_UNHIDE_QUESTION_FAIL = "HIDE_UNHIDE_QUESTION_FAIL";

// Reported User
export const VIEW_REPORTED_USER_LOADING = "VIEW_REPORTED_USER_LOADING";
export const VIEW_REPORTED_USER_SUCCESS = "VIEW_REPORTED_USER_SUCCESS";
export const VIEW_REPORTED_USER_FAIL = "VIEW_REPORTED_USER_FAIL";

// Reported Question
export const VIEW_REPORTED_QUESTION_LOADING = "VIEW_REPORTED_QUESTION_LOADING";
export const VIEW_REPORTED_QUESTION_SUCCESS = "VIEW_REPORTED_QUESTION_SUCCESS";
export const VIEW_REPORTED_QUESTION_FAIL = "VIEW_REPORTED_QUESTION_FAIL";

// Reported Solution
export const VIEW_REPORTED_SOLUTION_LOADING = "VIEW_REPORTED_SOLUTION_LOADING";
export const VIEW_REPORTED_SOLUTION_SUCCESS = "VIEW_REPORTED_SOLUTION_SUCCESS";
export const VIEW_REPORTED_SOLUTION_FAIL = "VIEW_REPORTED_SOLUTION_FAIL";

// View All Comments
export const GET_ALL_COMMENTS_LOADING = "GET_ALL_COMMENTS_LOADING";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_FAIL = "GET_ALL_COMMENTS_FAIL";

// Delete Comment
export const DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
