// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Login Using Email
export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

// Me Loading
export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

// ALl Users
export const ALL_USERS_LOADING = "ALL_USERS_LOADING";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

// All Questions
export const ALL_QUESTIONS_LOADING = "ALL_QUESTIONS_LOADING";
export const ALL_QUESTIONS_SUCCESS = "ALL_QUESTIONS_SUCCESS";
export const ALL_QUESTIONS_FAIL = "ALL_QUESTIONS_FAIL";

// All Solution
export const ALL_SOLUTIONS_LOADING = "ALL_SOLUTIONS_LOADING";
export const ALL_SOLUTIONS_SUCCESS = "ALL_SOLUTIONS_SUCCESS";
export const ALL_SOLUTIONS_FAIL = "ALL_SOLUTIONS_FAIL";

// ALL Categories
export const ALL_CATEGORIES_LOADING = "ALL_CATEGORIES_LOADING";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

// New Category
export const ADD_NEW_CATEGORY_LOADING = "ADD_NEW_CATEGORY_LOADING";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAIL = "ADD_NEW_CATEGORY_FAIL";
